# Generated by Django 4.1.5 on 2023-01-24 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_agentname_name_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnouncedLgaResults",
            fields=[
                (
                    "result_id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("lga_name", models.CharField(max_length=50)),
                ("party_abbreviation", models.CharField(max_length=4)),
                ("party_score", models.IntegerField()),
                ("entered_by_user", models.CharField(max_length=50)),
                (
                    "date_entered",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("user_ip_address", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="agentname",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
