# Generated by Django 4.1.5 on 2023-01-24 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_announcedwardresults"),
    ]

    operations = [
        migrations.CreateModel(
            name="LGA",
            fields=[
                (
                    "uniqueid",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("lga_id", models.IntegerField()),
                ("lga_name", models.CharField(max_length=50)),
                ("state_id", models.IntegerField()),
                ("lga_description", models.TextField()),
                ("entered_by_user", models.CharField(max_length=50)),
                (
                    "date_entered",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("user_ip_address", models.CharField(max_length=50)),
            ],
        ),
    ]
