# Generated by Django 4.1.5 on 2023-01-24 17:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_lga"),
    ]

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partyid", models.CharField(max_length=11)),
                ("partyname", models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                ("state_id", models.IntegerField(primary_key=True, serialize=False)),
                ("state_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "uniqueid",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("ward_id", models.IntegerField()),
                ("ward_name", models.CharField(max_length=50)),
                ("ward_description", models.TextField()),
                ("entered_by_user", models.CharField(max_length=50)),
                (
                    "date_entered",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("user_ip_address", models.CharField(max_length=50)),
                (
                    "lga_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.lga"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PollingUnit",
            fields=[
                (
                    "uniqueid",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("polling_unit_id", models.IntegerField()),
                ("uniquewardid", models.IntegerField()),
                ("polling_unit_number", models.CharField(max_length=50)),
                ("polling_unit_name", models.CharField(max_length=50)),
                ("polling_unit_description", models.TextField()),
                ("lat", models.CharField(max_length=255)),
                ("long", models.CharField(max_length=255)),
                ("entered_by_user", models.CharField(max_length=50)),
                (
                    "date_entered",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("user_ip_address", models.CharField(max_length=50)),
                (
                    "lga_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.lga"
                    ),
                ),
                (
                    "ward_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.ward"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="agentname",
            name="pollingunit_uniqueid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="polls.pollingunit"
            ),
        ),
        migrations.AlterField(
            model_name="lga",
            name="state_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="polls.state"
            ),
        ),
    ]
