# Generated by Django 4.1.5 on 2023-01-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0009_rename_pollingunit_uniqueid_agentname_pollingunit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ward",
            name="lga",
        ),
        migrations.AddField(
            model_name="ward",
            name="lga_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
