# Generated by Django 4.1.5 on 2023-01-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0011_alter_pollingunit_polling_unit_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollingunit",
            name="entered_by_user",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
