# Generated by Django 4.1.5 on 2023-01-24 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0012_alter_pollingunit_entered_by_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollingunit",
            name="date_entered",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pollingunit",
            name="user_ip_address",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
