# Generated by Django 4.1.5 on 2023-01-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0014_remove_pollingunit_lga_pollingunit_lga_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pollingunit",
            name="ward",
        ),
        migrations.AddField(
            model_name="pollingunit",
            name="ward_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
