# Generated by Django 4.1.5 on 2023-01-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0015_remove_pollingunit_ward_pollingunit_ward_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agentname",
            name="pollingunit",
        ),
        migrations.AddField(
            model_name="agentname",
            name="pollingunit_uniqueid",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
