# Generated by Django 4.1.5 on 2023-01-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0016_remove_agentname_pollingunit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcedstateresults",
            name="party_abbreviation",
            field=models.CharField(max_length=10),
        ),
    ]
