# Generated by Django 4.1.5 on 2023-01-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0017_alter_announcedstateresults_party_abbreviation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcedpuresults",
            name="party_abbreviation",
            field=models.CharField(max_length=10),
        ),
    ]
